const teamData = [
  {
    id: 1,
    name: "Zain Mustafa",
    position: "PROJECT LEAD",
    bio: "Architect. Educationist. Cultural Anthropologist",
    history: [
      "Graduate of Parsons School of Design, and recipient of a full scholarship for an MA at Columbia University. Currently pursuing PhD.",
      "Executive Director for ERA",
      "Founder IRVI (Indus River Valley Institute) - Pakistan's first Culture & Heritage Think Tank",
      "Founder Cube Edutour - a unique heritage architecture education tourism initiative",
      "President Society for the Protection of Animal",
      "Advisory board Pakistan Chowk Community Center",
      "An acclaimed architect, former teacher at the Indus Valley School of Art & Architecture, and a true global citizen.",
      "His portfolio boasts prestigious projects such as NIC Karachi, sophisticated restaurants like Tao, and the transformation of the Karachi Zoo into an animal-centric, sensitive space.",
      "Currently at the forefront of crafting the enchanting Butterfly Effect Universe, leading the endeavor to bring forth a magical experience that transcends ordinary boundaries.",
    ],
    img: "/assets/images/team/zain_mustafa.png",
  },
  {
    id: 2,
    name: "Shahnaz Wazir Ali",
    position: "Advisory Board Member",
    bio: `Sitara-e-Imtiaz for services to education (2016)
    Educationist. Social Sector Development Expert. Policy Specialist. Women's Rights Activist.`,
    history: [
      "Shahnaz Wazir Ali, a distinguished figure with over four decades of experience. Her impactful work extends to critical areas such as Education and Public Sector Reform, Polio Eradication, Family Planning, Population, and Social Protection, shaping policies nationally and globally. Since 1965, she has championed community education as a Trustee of Education Trust Nasra School. She served two terms in Pakistan's National Assembly, as Special Assistant to the Prime Minister, and held the esteemed position of Minister of State for Education making substantial contributions to educational reforms. Since 2013, she has presided over SZABIST University, overseeing multiple campuses. She also contributed her expertise internationally as a former World Bank Senior Education Specialist. Her involvement in numerous national and international boards, including IBA and UNESCO, underscores her leadership in the field.",
      "Her academic achievements include a Master's in Education from the University of Arkansas, USA, and certifications from Trenton College, New Jersey, and Harvard University.",
      "Former Minister of State for Education, Government of Pakistan",
      "Devoted her life to nurturing potential future leaders of Pakistan",
      "Brings an extremely erudite understanding of the power of pedagogy, structure of education in Pakistan and how to create schools of excellence within our private and public systems.",
    ],
    img: "/assets/images/team/shahnaz_wazir_ali.png",
  },
  {
    id: 3,
    name: "Hisham Youssef",
    position: "Advisory Board Member",
    bio: "AIA RIBA. Architect. Educator. Mentor. Photographer. Writer.",
    history: [
      "Hisham is an accomplished design professional with over 30 years of architectural design experience, at leading international design firms. He has lived, traveled and worked in the USA, Asia Pacific, Australia, and the Middle East. His diverse cultural background, both personally and professionally, provides him with a unique point of view in his approach to design and teaching. He has been based in Shanghai since 2011, and Associate Professor at Soochow University School of Architecture since 2017.",
      "Hisham is a native of Egypt where he grew up. He completed his undergraduate studies at Harvard University in Applied Mathematics, and later received his Master of Architecture from Columbia University. He is a licensed architect in NY State, a member of the American Institute of Architects, and co-founder of the AIA Middle East and Shanghai Chapters. When not working he photographs disappearing heritage in China for his work “Vanishing_”, and frequently writes about culture and travel issues. He is a collector of contemporary art, and an avid cook.",
      "Global citizen.",
      "Previously worked in Dubai as the Vice President of Gensler, the worlds largest Architecture firm.",
      "Currently, Associate Professor at Soochow University School of Architecture.",
      "Hisham brings an intellectually stimulating perspective, offering fresh and globally relevant  insights into large-scale construction across diverse cultures and climates, while also fostering an innovative vision for design education and an unwavering commitment to precision in every detail.",
    ],
    img: "/assets/images/team/hisham_youssef.jpg",
  },
  {
    id: 4,
    name: "Musharaf Hai",
    position: "Advisory Board Member",
    bio: "Sitara-e-Imtiaz for outstanding business achievements (2005). Chevalier de l'Ordre national du Merite (2011). Business Leader. Entrepreneur. Philanthropist.",
    history: [
      "Musharaf's diverse career began with Unilever Pakistan in 1983. Over 23 years, she held various roles from brand management to country operations. She also had a crucial role at Unilever's London Headquarters, overseeing Asia Pacific and Africa Middle East. In Pakistan, she oversaw the Ice Cream acquisition, became a Unilever Board Director, and later served as National Sales Director. From July 2001 to September 2006, she was Chairman & CEO.  She also served as head of Consumer banking of CitiBank Pakistan. In 2008, she joined L'Oreal, launching their Pakistan business.",
      "Her influence extends beyond the corporate realm, with board positions in education, banking, NGOs, and the health sector. She has actively participated in government policy groups. Her passion for wellness, the arts, and talent development, exemplify her multi-faceted career.",
      "Her educational background, including degrees from the London School of Economics and Boston University.",
      "Established corporate leader - Ex Unilever, Citibank Pakistan, and L'Oreal.",
      "Practical knowledge and experience of transforming ideas into reality.",
      "She understands how to reach a pan-national customer base within a global brand ethos, is an invaluable experience base which can help build brand BEU in a scalable model.",
    ],
    img: "/assets/images/team/musharaf_hai.jpg",
  },
  {
    id: 5,
    name: "Ben Schmidt",
    position: "Advisory Board Member",
    bio: "Doctorate in Philosophy. Visionary. Education Leader. Global Partnership Expert.",
    history: [
      "With a deep passion for education's future, Ben Schmidt is a global education leader. He has a tremendous track record of forming high-performing teams, forging partnerships, and expanding into new markets.",
      "Ben's journey with Cambridge International began in 2012 as Regional Director for Southeast Asia & Pacific, establishing the organization's first regional team and managing the East Asia team for three years. In August 2022, he became Director of the International Network at Cambridge International, nurturing global school relationships and overseeing nine regional teams. Previously, Ben advised on educational projects, collaborating with architectural teams. Currently based in Singapore, his professional life includes stints in Germany, the United States, Switzerland, England, and India. His unwavering commitment to education's entrepreneurial, socially impactful future drives his work.",
      "A trained lawyer, holding a master's in education, and a doctorate in philosophy, Ben blends academia and commerce.",
      "Global citizen.",
      "Currently, Director of the International Network at Cambridge.",
      "Leading the Cambridge Education Board assessment team, brings a deep and globally sound understanding of how a combination of orthodox and creative curricula focused on curiosity, imagination and innovation in critical thought brings a refinement opportunity to any learning program designed and developed at BEU, for a contemporary national and international student profile. Very relevant to BEU future with collaborations and exchange programs for teachers and students.",
    ],
    img: "/assets/images/team/ben_schmidt.png",
  },
  {
    id: 6,
    name: "Samia Liaqual Ali Khan",
    position: "Advisory Board Member",
    bio: "Strategic leader. Innovator. Socio-economic change expert.",
    history: [
      "With over two decades of experience, Samia's career centers on designing and implementing human impact programmes on a global scale.  As the granddaughter of Pakistan's first women's rights activist and APWA founder, Samia deeply comprehends the challenges faced by marginalized communities.  She is celebrated for her unwavering commitment to executing visionary programs with empathy and determination.",
      "Samia served as the Programme Director for the US$150 million National Poverty Graduation Programme, backed by the Government of Pakistan and the International Fund for Agriculture Development. She also boasts nearly a decade of experience with International NGOs in the United Kingdom. She excels in managing financial / donor partnerships, and  fostering high-performing teams.",
      "Samia holds a Masters of Public Administration from Columbia University's School of International and Public Affairs and an MSc in Development Studies, International Development from SOAS University of London.",
      "With decades of field experience through PPAF she brings knowledge and hands on experience of the needs of rural and under privileged Pakistan.",
      'Her solid understanding of pvt-public relationships and the modus operandi of the NGO sector, how the systems work, the dispersion of "assets" would be a knowledge base greatly beneficial to BEU.',
      "Plus her own lineage as grand daughter to Raana Liaquat Ali Khan brings a love/devotion for Pakistan and its future leaders like none other.",
    ],
    img: "/assets/images/team/samia_liaquat_ali.png",
  },
  {
    id: 7,
    name: "Shereen Abdullah",
    position: "Advisory Board Member",
    bio: "Butterfly Conservationist. The Butterfly Lady.",
    history: [
      "For the past 16 years, Shereen has dedicated herself to the preservation and study of butterfly species within Karachi. Her extensive efforts revolve around the conservation of various Swallowtail butterfly species in Karachi, notably Lime butterflies and Mormons. She has also conducted thorough research on other species such as Plain Tigers/African Monarchs and Pioneers/Capers Whites, focusing on both the butterflies themselves and their host plants.",
      "Beyond her endeavors to support these species in their natural habitat, Shereen has also meticulously observed and examined various other butterfly species that inhabit Karachi, closely studying their interactions with host plants.",
      "Her conservation initiative is founded on two crucial pillars: awareness sessions and rescue services. Shereen actively spreads awareness by conducting educational programs in numerous schools and institutions across Karachi. Furthermore, she takes an active role in leading a butterfly club, where she imparts intricate skills and techniques for nurturing caterpillars to students.",
      "Her educational background encompasses a Master's program in public administration, with a specialized focus on HR and finance, achieved at DPA from Karachi University.",
      "As she looks ahead, her aspirations extend to expanding her efforts to encompass a broader array of butterfly and moth species not only within Pakistan but also globally.",
      'Known as "The Butterfly Lady" in Pakistan.',
      "She brings to the BEU vision the perfect knowledge, experience and passion for butterfly conservation and release back into the wild towards the betterment of climate and the planet. This crystal-clear soulful devotion and dedication to a crucial element of the BEU vision will be priceless asset for the project.",
    ],
    img: "/assets/images/team/shereen_abdullah.png",
  },
  {
    id: 8,
    name: "Shahjahan Chaudhry",
    position: "Advisory Board Member",
    bio: "Entrepreneur.  Venture builder. Digital Expert.",
    history: [
      "Shahjahan Chaudhry is a dynamic entrepreneur known for his remarkable contributions and expertise in AI, Edtech, and Fintech sectors. Shahjahan plays a pivotal role in shaping the future of these industries through venture development, project financing, and corporate innovation on a global scale.",
      "Beginning as the CEO of HOMEXPRESS, he entered into the entrepreneurial realm, crafting a premium direct-mail magazine. His expertise expanded at Team::ants Pvt Ltd, where he partnered with prominent fashion, food, and financial brands, leaving an indelible mark on Pakistan's digital landscape. Notably, Shahjahan served as Director at the National Incubation Center Karachi, where he led the launch of over 100 start-ups. His career also includes founding Team::ants Pvt Ltd, a pioneering Digital & Social Agency, and contributing to organizations like P@SHA and PeaceNiche. He currently serves as the Managing Director of Machinelab Ventures LDA, and Board Member for Encore Pay, and Indus River Valley Institute.",
      "Shahjahan's entrepreneurial spirit and digital prowess continue to drive innovation and change the landscape of multiple industries.",
      "Epitomizes the entrepreneurial spirit.",
      "Founder of many successful businesses, including NIC Karachi.",
      "Brings a very carefully thought through visionary world view for the betterment of Pakistan's youth through the language of technology.",
    ],
    img: "/assets/images/team/shahjahan_chaudhry.png",
  },
];

export default teamData;
